webtalk_init -webtalk_dir C:/Users/juanan/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar 18 22:30:19 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "436bd4fd-cac3-4f0b-863d-10ed48c35c79" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "097ec68604c9436d9d175bd147be34cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2527 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "77773415 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "11.68_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15132_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3760455988 -regid "" -xml C:/Users/juanan/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/juanan/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/juanan/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
