webtalk_init -webtalk_dir C:/Users/Yo Yo/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 19 20:45:36 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2035080" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "482c81c7-cd0d-4b04-8d37-341c491e7110" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "097ec68604c9436d9d175bd147be34cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "61" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8320 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3516 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7208_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3463813739 -regid "" -xml C:/Users/Yo Yo/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Yo Yo/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Yo Yo/Desktop/Nueva-cafetera/Cafetera/Cafetera.sim/sim_1/behav/xsim/xsim.dir/tb_clk_divider_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
